"use client"

import { useState } from "react"
import { 
  FileSpreadsheet, 
  Smartphone, 
  Headphones, 
  RotateCcw, 
  History,
} from "lucide-react"

import Card from "@/shared/ui/Card"
import CardHeader from "@/features/omnix/components/CardHeader"

// Komponen KPI yang rapi
function KpiInfoCard({ title, value }: { title: string; value: string }) {
  return (
    <div className="rounded-lg border border-(--c-border) bg-(--c-control) p-4">
      <div className="text-[10px] font-bold uppercase tracking-widest text-(--c-muted)">{title}</div>
      <div className="mt-2 text-sm font-bold text-(--c-text)">{value}</div>
    </div>
  )
}

export default function ReportCenterPage() {
  const [module, setModule] = useState<"digital" | "voice">("digital")

  return (
    <div className="p-6 space-y-5 max-w-[1400px] mx-auto">
      {/* HEADER */}
      <Card>
        <div className="flex items-center justify-between p-6">
          <div>
            <h1 className="flex items-center gap-3 text-3xl font-bold text-(--c-text)">
              <FileSpreadsheet className="h-8 w-8 text-sky-500" />
              Report Center
            </h1>
            <p className="mt-2 text-sm text-(--c-muted)">
              Generate and export operational reports in Microsoft Excel format.
            </p>
          </div>

          <button className="flex items-center gap-2 rounded-xl border border-(--c-border) bg-(--c-control) px-4 py-2.5 text-sm font-medium transition-colors hover:bg-(--c-surface)">
            <History className="h-4 w-4" />
            Export History
          </button>
        </div>
      </Card>

      {/* MODULE SELECTOR */}
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {[
          { id: "digital", label: "Digital Traffic", desc: "Omnichannel Report", icon: Smartphone },
          { id: "voice", label: "Voice Traffic", desc: "Call Center Report", icon: Headphones },
        ].map((item) => (
          <button
            key={item.id}
            onClick={() => setModule(item.id as "digital" | "voice")}
            className={`
              group rounded-xl border p-5 text-left transition-all
              ${
                module === item.id
                  ? "border-sky-500 bg-sky-500/10"
                  : "border-(--c-border) bg-(--c-surface) hover:border-sky-500/40 hover:bg-(--c-control)"
              }
            `}
          >
            <div className="flex items-center gap-4">
              <div className={`flex h-11 w-11 items-center justify-center rounded-lg ${module === item.id ? "bg-sky-500/15" : "bg-(--c-control)"}`}>
                <item.icon className="h-6 w-6 text-sky-500" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-(--c-text)">{item.label}</h2>
                <p className="mt-1 text-sm text-(--c-muted)">{item.desc}</p>
              </div>
            </div>
          </button>
        ))}
      </div>

      {/* CONFIGURATION CARD */}
      <Card>
        <CardHeader title="Report Configuration" />
        <div className="p-6 grid grid-cols-3 gap-6">
          {["Report Type", "Channel", "Brand", "Main Category", "Start Date", "End Date"].map((label) => (
            <div key={label} className="space-y-2">
              <label className="text-xs font-semibold uppercase text-(--c-muted)">{label}</label>
              <input 
                type={label.includes("Date") ? "date" : "text"} 
                className="w-full rounded-lg border border-(--c-border) bg-(--c-control) p-3 text-sm outline-none focus:border-sky-500 transition-all" 
              />
            </div>
          ))}
        </div>
        
        {/* REPORT INFO KPI */}
        <div className="px-6 pb-6 pt-0">
          <div className="text-xs font-bold uppercase text-(--c-muted) mb-4">Report Preview Stats</div>
          <div className="grid grid-cols-4 gap-4">
            <KpiInfoCard title="Total Records" value="15,240" />
            <KpiInfoCard title="Output Format" value="XLSX" />
            <KpiInfoCard title="Source" value="Omnix DB" />
            <KpiInfoCard title="Generated By" value="Admin" />
          </div>
        </div>

        <div className="flex justify-end gap-3 p-6 pt-0 border-t border-(--c-border) pt-6">
          <button className="px-6 py-2.5 rounded-lg border border-(--c-border) font-semibold text-sm hover:bg-(--c-control)">Reset</button>
          <button className="px-6 py-2.5 rounded-lg bg-sky-600 text-white font-semibold text-sm hover:bg-sky-700">Export Excel</button>
        </div>
      </Card>
    </div>
  )
}