"use client"

import { useState } from "react"
import { 
  FileSpreadsheet, Smartphone, Headphones, 
  Download, RotateCcw, History, LayoutDashboard 
} from "lucide-react"

import Card from "@/shared/ui/Card"
import CardHeader from "@/features/omnix/components/CardHeader"

// Komponen KPI yang rapi dengan fixed padding dan alignment
function KpiInfoCard({ title, value }: { title: string; value: string }) {
  return (
    <div className="rounded-lg border border-(--c-border) bg-(--c-control) p-4">
      <div className="text-[10px] font-bold uppercase tracking-widest text-(--c-muted)">{title}</div>
      <div className="mt-2 text-sm font-bold text-(--c-text)">{value}</div>
    </div>
  )
}

export default function ReportCenterPage() {
  const [module, setModule] = useState<"digital" | "voice">("digital")

  return (
    <div className="p-6 space-y-8">
      {/* HEADER */}
      <div className="flex items-center justify-between border-b border-(--c-border) pb-6">
        <div>
          <h1 className="text-2xl font-bold text-(--c-text) flex items-center gap-3">
            <LayoutDashboard className="text-sky-500" /> Report Center
          </h1>
        </div>
        <button className="flex items-center gap-2 rounded-lg border border-(--c-border) bg-(--c-surface) px-4 py-2 text-sm font-semibold hover:bg-(--c-control)">
          <History size={16} /> Export History
        </button>
      </div>

      {/* MODULE SELECTOR */}
      <div className="grid grid-cols-2 gap-6">
        {[
          { id: "digital", label: "Digital Traffic", desc: "Omnichannel analytics" },
          { id: "voice", label: "Voice Traffic", desc: "Call center metrics" }
        ].map((item) => (
          <button
            key={item.id}
            onClick={() => setModule(item.id as any)}
            className={`p-6 rounded-xl border-2 text-left transition-all ${
              module === item.id 
                ? "border-sky-500 bg-sky-500/5" 
                : "border-(--c-border) bg-(--c-surface) hover:border-sky-500/30"
            }`}
          >
            <h2 className="text-lg font-bold text-(--c-text)">{item.label}</h2>
            <p className="text-sm text-(--c-muted) mt-1">{item.desc}</p>
          </button>
        ))}
      </div>

      {/* CONFIGURATION CARD */}
      <Card>
        <CardHeader title="Report Configuration" />
        <div className="p-6 grid grid-cols-3 gap-6">
          {["Report Type", "Channel", "Brand", "Main Category", "Start Date", "End Date"].map((label) => (
            <div key={label} className="space-y-2">
              <label className="text-xs font-semibold uppercase text-(--c-muted)">{label}</label>
              <input 
                type={label.includes("Date") ? "date" : "text"} 
                className="w-full rounded-lg border border-(--c-border) bg-(--c-control) p-3 text-sm outline-none focus:border-sky-500" 
              />
            </div>
          ))}
        </div>
        
        {/* REPORT INFO KPI - Ini bagian yang Anda maksud berantakan */}
        <div className="px-6 pb-6 pt-0">
          <div className="text-xs font-bold uppercase text-(--c-muted) mb-4">Report Preview Stats</div>
          <div className="grid grid-cols-4 gap-4">
            <KpiInfoCard title="Total Records" value="15,240" />
            <KpiInfoCard title="Output Format" value="XLSX" />
            <KpiInfoCard title="Source" value="Omnix DB" />
            <KpiInfoCard title="Generated By" value="Admin" />
          </div>
        </div>

        <div className="flex justify-end gap-3 p-6 pt-0 border-t border-(--c-border) pt-6">
          <button className="px-6 py-2.5 rounded-lg border border-(--c-border) font-semibold text-sm">Reset</button>
          <button className="px-6 py-2.5 rounded-lg bg-sky-600 text-white font-semibold text-sm">Export Excel</button>
        </div>
      </Card>
    </div>
  )
}