import json
from app.core.supabase import supabase

res = supabase.table("principal_mapping").select("*").order("id").execute()
rows = res.data or []

lines = []
lines.append('"""Principal Group and Principal Category mapping engine.')
lines.append('')
lines.append('Synchronized directly with public.principal_mapping table in Supabase.')
lines.append('Maps raw case detail_subcategory to standardized Principal reporting dimensions')
lines.append('without altering raw database records.')
lines.append('"""')
lines.append('')
lines.append('from typing import Dict, Optional, Tuple')
lines.append('')
lines.append('# Exact 58 rules from Supabase public.principal_mapping table')
lines.append('PRINCIPAL_DETAIL_MAPPING: Dict[str, Tuple[str, str, bool]] = {')

for r in rows:
    det = r["omnix_detail_subcategory"].strip()
    grp = r["principal_group"].strip()
    cat = r["principal_category"].strip()
    inc = bool(r["include_report"])
    lines.append(f"    {det!r}: ({grp!r}, {cat!r}, {inc!r}),")

lines.append("}")
lines.append("")
lines.append("")
lines.append("def map_principal_dimensions(")
lines.append("    main_category: Optional[str],")
lines.append("    subcategory: Optional[str],")
lines.append("    detail_subcategory: Optional[str],")
lines.append(") -> Tuple[str, str, bool]:")
lines.append('    """Map case category fields to (Principal Group, Principal Category, Include in Report)."""')
lines.append('    d = (detail_subcategory or "").strip()')
lines.append('    s = (subcategory or "").strip()')
lines.append('    m = (main_category or "").strip()')
lines.append("")
lines.append("    # 1. Exact match in Supabase principal_mapping table")
lines.append("    for k, (grp, cat, inc) in PRINCIPAL_DETAIL_MAPPING.items():")
lines.append("        if k.lower() == d.lower():")
lines.append("            return (grp, cat, inc)")
lines.append("")
lines.append("    # 2. Match subcategory name if detail_subcategory is empty or equals subcategory")
lines.append("    for k, (grp, cat, inc) in PRINCIPAL_DETAIL_MAPPING.items():")
lines.append("        if k.lower() == s.lower():")
lines.append("            return (grp, cat, inc)")
lines.append("")
lines.append("    # 3. Fuzzy heuristic fallback")
lines.append("    d_lower = d.lower()")
lines.append("    s_lower = s.lower()")
lines.append("    m_lower = m.lower()")
lines.append("")
lines.append('    if any(kw in d_lower or kw in s_lower for kw in ["spam", "tidak dijawab", "sosmed activity", "mention", "comment", "story"]):')
lines.append('        return ("", "", False)')
lines.append("")
lines.append('    if "baterai" in d_lower or "battery" in d_lower:')
lines.append('        return ("Failure", "Battery Issue", True)')
lines.append('    if "spare part" in d_lower or "sparepart" in d_lower or "part" in d_lower:')
lines.append('        return ("Failure", "Spare Part Issue", True)')
lines.append('    if "motor" in d_lower:')
lines.append('        return ("Failure", "Motor Issue", True)')
lines.append('    if "sensor" in d_lower:')
lines.append('        return ("Failure", "Sensor Issue", True)')
lines.append('    if "air" in d_lower or "cwt" in d_lower or "dwt" in d_lower:')
lines.append('        return ("Failure", "Water System Issue", True)')
lines.append('    if "rusak" in d_lower or "kendala" in d_lower or "kendala" in s_lower:')
lines.append('        return ("Failure", "General Device Failure", True)')
lines.append("")
lines.append('    if "map" in d_lower:')
lines.append('        return ("How to use", "Map creation", True)')
lines.append('    if "pair" in d_lower or "aplikasi" in d_lower or "app" in d_lower:')
lines.append('        return ("How to use", "App connection", True)')
lines.append('    if "rawat" in d_lower or "aksesoris" in d_lower or "clean" in d_lower:')
lines.append('        return ("How to use", "Parts maintenance", True)')
lines.append('    if "panduan" in m_lower or "panduan" in s_lower:')
lines.append('        return ("How to use", "New machines", True)')
lines.append("")
lines.append('    if "status" in d_lower or "progress" in d_lower:')
lines.append('        return ("Aftersale-Service inquiry", "Repair Progress", True)')
lines.append('    if "biaya" in d_lower or "harga" in d_lower:')
lines.append('        return ("Aftersale-Service inquiry", "Repair Fees", True)')
lines.append('    if "service" in s_lower or "service" in d_lower:')
lines.append('        return ("Aftersale-Service inquiry", "Repair centre", True)')
lines.append("")
lines.append('    if "promo" in s_lower or "diskon" in d_lower or "produk" in s_lower or "spesifikasi" in d_lower:')
lines.append('        return ("Pre-sales", "Product", True)')
lines.append('    if "kol" in s_lower or "sponsor" in d_lower:')
lines.append('        return ("Pre-sales", "Agency/Cooperation Consulting", True)')
lines.append("")
lines.append('    return ("", "", True)')
lines.append("")
lines.append("")
lines.append("def enrich_principal_row(row: dict) -> dict:")
lines.append('    """Ensure a row has principal_group and principal_category populated from principal_mapping."""')
lines.append("    row_copy = dict(row)")
lines.append('    pg = row_copy.get("principal_group")')
lines.append('    pc = row_copy.get("principal_category")')
lines.append("")
lines.append('    if not pg or not pc or str(pg).strip().lower() in ["", "none", "null"]:')
lines.append("        grp, cat, _ = map_principal_dimensions(")
lines.append('            row_copy.get("main_category"),')
lines.append('            row_copy.get("subcategory"),')
lines.append('            row_copy.get("detail_subcategory"),')
lines.append("        )")
lines.append("        if grp:")
lines.append('            row_copy["principal_group"] = grp')
lines.append("        if cat:")
lines.append('            row_copy["principal_category"] = cat')
lines.append("")
lines.append("    return row_copy")
lines.append("")

with open("app/services/principal_mapper.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Generated app/services/principal_mapper.py with {len(rows)} rules from Supabase table successfully.")
